### ISSUE TITLE
publish to docker hub

### ISSUE THREAD

**Issue by softprops** [openlawteam/scalafmt-ci#4]
This saves the time in ci spending building your image

**Comment by mroth** [comment]
Thanks for the idea! 

The current Dockerfile does pretty much nothing on top of the default scalafmt-native image on Docker Hub, just adds a few GitHub Actions specific metadata fields and copies a tiny wrapper script. From looking at the logs, this takes <= 2 seconds after downloading the core images.

A larger chunk of time is downloading the scalafmt-native image from docker hub, which seems to take 6-7 seconds despite only being 9.63MB compressed. Based on this, if we really wanted to cut out a few seconds, I'm guessing the thing to do would be try hosting an image on GitHub Packages, or perhaps even just downloading the scalafmt-native Linux binary directly from the releases page (which is hosted on GitHub, thus within their datacenter) to the GHA environment.

(If you want to take a stab at this, feel free to submit as a PR along with test runs showing the speed change.)
